### ISSUE TITLE
Datasheet I2C commands

### ISSUE THREAD

**Issue by dizcza** [sitronlabs/SitronLabs_Honeywell_HSC_Arduino_Library#1]
Thanks for publishing this code.

I have an I2C Honeywell sensor with a 500 Pa amplitude range (±2 inH2O), and I'm trying to update your code for this sensor.

I cannot find I2C description in the official Honeywell datasheet. In particular, where did you get these lines from:

```c
    const double m_raw_min = 1638.3;   //!< 10% of 2^14 counts, or 0x0666
    const double m_raw_max = 14744.7;  //!< 90% of 2^14 counts, or 0x399A
```

is it your hack or is it written in the docs?

**Comment by dizcza** [comment]
```c++
#include "hsc.h"

hsc_i2c hsc;

const double m_pressure_min_pa = -500;
const double m_pressure_max_pa = 500;

const double m_raw_min = 0;
const double m_raw_max = 1 << 14;

void setup() {
  Serial.begin(115200);
  while (!Serial);
  Wire.begin(21, 22);
  hsc.setup(Wire);
}

void loop() {
  delay(500);
  uint16_t pressure_raw;
  uint16_t temperature_raw;
  hsc.data_get(pressure_raw, temperature_raw);
  double temperature_c = (((double)temperature_raw / 2047.0) * 200.0) - 50.0;
  double pressure_pa = ((((double)pressure_raw - m_raw_min) * (m_pressure_max_pa - m_pressure_min_pa)) / (m_raw_max - m_raw_min)) + m_pressure_min_pa;

  Serial.printf("%d -> %.3f Pa, %d -> %.3f C\n", pressure_raw, pressure_pa, temperature_raw, temperature_c);
}
```

Temperature conversion works fine but pressure output does not change much when I blow at one of the ports with another port enclosed in a mechanical low-pass filter (I expect 10+ Pa change in the output).

```
8429 -> 14.465 Pa, 789 -> 27.088 C
8432 -> 14.648 Pa, 789 -> 27.088 C
8436 -> 14.893 Pa, 789 -> 27.088 C
8439 -> 15.076 Pa, 789 -> 27.088 C
8436 -> 14.893 Pa, 789 -> 27.088 C
8439 -> 15.076 Pa, 789 -> 27.088 C
8446 -> 15.503 Pa, 789 -> 27.088 C
8443 -> 15.320 Pa, 789 -> 27.088 C
8451 -> 15.808 Pa, 789 -> 27.088 C
8453 -> 15.930 Pa, 789 -> 27.088 C
8453 -> 15.930 Pa, 789 -> 27.088 C
8455 -> 16.052 Pa, 789 -> 27.088 C
8458 -> 16.235 Pa, 789 -> 27.088 C
8465 -> 16.663 Pa, 789 -> 27.088 C
8469 -> 16.907 Pa, 789 -> 27.088 C
```

----

UPD

The code seem to work fine, I just needed to decrease the delay to see short blows of air.

But I don't understand the `m_raw_min` and `m_raw_max` constants. These should be 0 and 2^14, shouldn't they?

**Comment by nschurando** [comment]
Hi Danylo,
I am currently travelling, so I can"t give you a detailed answer, but hopefully some pointers will help.

First, look at the transfer function for your specific sensor. With it you should be able to determine pmin and pmax for your sensor.
![image](https://github.com/sitronlabs/SitronLabs_Honeywell_HSC_Arduino_Library/assets/1104104/f5b554bf-31b8-4097-9741-380c2a6f1df2)

Then refer at figure 2 "transfer function limits" for "digital versions"
![image](https://github.com/sitronlabs/SitronLabs_Honeywell_HSC_Arduino_Library/assets/1104104/4372f4b5-79a4-4b07-a343-192eeb2276ab)

Let me know if this helps.

Regards,

Nicolas

**Comment by dizcza** [comment]
True! Somehow, I skipped this equation.

Thanks.

I'm closing the issue but I have other questions, as a user.

I have an SSCDRRN002ND2A3, an I2C sensor.

Have you noticed zero drifts of the output at 100+ Hz sampling rate? By zero drift, I mean the output diff pressure experiences ups and downs with time at sub-herz frequencies (< 1 Hz) when no external pressure is applied, and both ports are opened. I expect the output to be constant (not necessarily zero, just some constant value) but I see the drift of ~2 Pa in one minute - that's a lot. It could be environmental changes but with both ports opened and placed close to each other - I doubt the origin now.

**Comment by nschurando** [comment]
I haven't noticed any drift, but also I haven't looked for drifts.
However, 2 Pascals sound like an incredibly small variation.
I don't know the specs of the sensor you are using but I would imagine it is still well below the total error band?

**Comment by dizcza** [comment]
> However, 2 Pascals sound like an incredibly small variation.
I don't know the specs of the sensor you are using but I would imagine it is still well below the total error band?

Not really. The error band is 0.8 Pa (amplitude peak-to-peak) when both ports are opened and I see no noticeable fluctuation (drift), and this value matches with the P2P error of other sensors I have (different manufacturers).

When I connect a mechanical filter with the cutoff freq of 0.1Hz to one of the ports, the fluctuation amplitude rises significantly, but that's another story - environmental factors start to influence it.
